FROM centos:centos7.9.2009

LABEL MAINTAINER "www.witersen.com 2022-12-04"

# 时间同步
ENV TZ=Asia/Shanghai \
    DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone

# 编码修改
RUN localedef -c -i en_US -f UTF-8 C.UTF-8 \
    && echo 'LANG="C.UTF-8"' >> /etc/sysconfig/i18n \
    && echo 'LC_ALL="C.UTF-8"' >> /etc/sysconfig/i18n \
    && echo 'export LANG="C.UTF-8"' >> /etc/profile \
    && echo 'export LC_ALL="C.UTF-8"' >> /etc/profile

RUN echo -e "[WandiscoSVN]\nname=Wandisco SVN Repo\nbaseurl=http://opensource.wandisco.com/centos/\$releasever/svn-1.9/RPMS/\$basearch/\nenabled=1\ngpgcheck=0" > /etc/yum.repos.d/wandisco-svn.repo \
    && yum install -y epel-release yum-utils \
    && rpm -Uvh https://mirrors.aliyun.com/remi/enterprise/remi-release-7.rpm \
    && yum-config-manager --enable remi-php74 \
    && yum install -y php php-common php-cli php-fpm php-json php-mysqlnd php-mysql php-pdo php-process php-json php-gd php-bcmath php-ldap\
    && yum install -y httpd mod_dav_svn mod_ldap mod_php subversion subversion-tools \
    && yum install -y cyrus-sasl cyrus-sasl-lib cyrus-sasl-plain \
    && yum install -y zip unzip which \
    && yum install -y cronie at \
    && yum clean all

# 配置文件
ADD data/ /home/svnadmin/
RUN cd /home/svnadmin/ \
    && mkdir -p backup \
    && mkdir -p crond \
    && mkdir -p rep \
    && mkdir -p temp \
    && mkdir -p templete/initStruct/01/branches \
    && mkdir -p templete/initStruct/01/tags \
    && mkdir -p templete/initStruct/01/trunk
RUN chown -R apache:apache /home/svnadmin/ && mkdir -p /run/php-fpm/

# 关闭PHP彩蛋
RUN sed -i 's/expose_php = On/expose_php = Off/g' /etc/php.ini

# 源码
ADD https://gitee.com/witersen/SvnAdminV2.0/releases/download/2.5.3/2.5.3.zip /var/www/html/
RUN cd /var/www/html && unzip 2.5.3.zip && rm -f 2.5.3.zip

ADD start.sh /root/start.sh
RUN chmod +x /root/start.sh

EXPOSE 80
EXPOSE 443
EXPOSE 3690

CMD ["/root/start.sh"]
